# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(351, 191)
        self.formLayout = QtWidgets.QFormLayout(LoginForm)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(LoginForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.password_label = QtWidgets.QLabel(LoginForm)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.username_label = QtWidgets.QLabel(LoginForm)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_input = QtWidgets.QLineEdit(LoginForm)
        self.username_input.setObjectName("username_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username_input)
        self.password_input = QtWidgets.QLineEdit(LoginForm)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_input)
        self.submit_button = QtWidgets.QPushButton(LoginForm)
        self.submit_button.setObjectName("submit_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.submit_button)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Health Tracker"))
        self.label.setText(_translate("LoginForm", "Health Tracker Login"))
        self.password_label.setText(_translate("LoginForm", "Password"))
        self.username_label.setText(_translate("LoginForm", "Username"))
        self.submit_button.setText(_translate("LoginForm", "Login"))
