from collections import namedtuple

suppliers = set()
Supplier = namedtuple('Supplier',['sno', 'sname', 'status', 'city'])
suppliers.add(Supplier("s1","Smith",20,"London"))
suppliers.add(Supplier("s2","Jones",10,"Paris"))
suppliers.add(Supplier("s3","Blake",30,"Paris"))
suppliers.add(Supplier("s4","Clark",20,"London"))
suppliers.add(Supplier("s5","Adams",30,"Athens"))

parts = set()
Part = namedtuple('Part',['pno', 'pname', 'color', 'weight', 'city'])
parts.add(Part("p1","Nut","Red",12,"London"))
parts.add(Part("p2","Bolt","Green",17,"Paris"))
parts.add(Part("p3","Screw","Blue",17,"Rome"))
parts.add(Part("p4","Screw","Red",14,"London"))
parts.add(Part("p5","Cam","Blue",12,"Paris"))
parts.add(Part("p6","Cog","Red",19,"London"))

projects = set()
Project = namedtuple('Project',['jno', 'jname', 'city'])
projects.add(Project("j1","Sorter","Paris"))
projects.add(Project("j2","Punch","Rome"))
projects.add(Project("j3","Reader","Athens"))
projects.add(Project("j4","Console","Athens"))
projects.add(Project("j5","Collator","London"))
projects.add(Project("j6","Terminal","Oslo"))
projects.add(Project("j7","Tape","London"))

spj = set()
SPJ = namedtuple('SPJ',['sno', 'pno', 'jno', 'qty'])
spj.add(SPJ("s1","p1","j1",200))
spj.add(SPJ("s1","p1","j4",700))
spj.add(SPJ("s2","p3","j1",400))
spj.add(SPJ("s2","p3","j2",200))
spj.add(SPJ("s2","p3","j3",200))
spj.add(SPJ("s2","p3","j4",500))
spj.add(SPJ("s2","p3","j5",600))
spj.add(SPJ("s2","p3","j6",400))
spj.add(SPJ("s2","p3","j7",800))
spj.add(SPJ("s2","p5","j2",100))
spj.add(SPJ("s3","p3","j1",200))
spj.add(SPJ("s3","p4","j2",500))
spj.add(SPJ("s4","p6","j3",300))
spj.add(SPJ("s4","p6","j7",300))
spj.add(SPJ("s5","p2","j2",200))
spj.add(SPJ("s5","p2","j4",100))
spj.add(SPJ("s5","p5","j5",500))
spj.add(SPJ("s5","p5","j7",100))
spj.add(SPJ("s5","p6","j2",200))
spj.add(SPJ("s5","p1","j4",100))
spj.add(SPJ("s5","p3","j4",200))
spj.add(SPJ("s5","p4","j4",800))
spj.add(SPJ("s5","p5","j4",400))
spj.add(SPJ("s5","p6","j4",500))
