# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_button1(object):
    def setupUi(self, button1):
        button1.setObjectName("button1")
        button1.resize(640, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(button1)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(button1)
        self.pushButton.setGeometry(QtCore.QRect(270, 230, 90, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(button1)
        self.buttonBox.accepted.connect(button1.accept)
        self.buttonBox.rejected.connect(button1.reject)
        QtCore.QMetaObject.connectSlotsByName(button1)

    def retranslateUi(self, button1):
        _translate = QtCore.QCoreApplication.translate
        button1.setWindowTitle(_translate("button1", "Dialog"))
        self.pushButton.setText(_translate("button1", "Press Me"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    button1 = QtWidgets.QDialog()
    ui = Ui_button1()
    ui.setupUi(button1)
    button1.show()
    sys.exit(app.exec_())
