# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/steven/Documents/Python_code/practice/GUI/PyQt5/Health_Tracker/h_tracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 372)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label, 0, QtCore.Qt.AlignHCenter)
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setObjectName("name_input")
        self.verticalLayout.addWidget(self.name_input)
        self.weight_label = QtWidgets.QLabel(self.centralwidget)
        self.weight_label.setObjectName("weight_label")
        self.verticalLayout.addWidget(self.weight_label, 0, QtCore.Qt.AlignHCenter)
        self.weight_input = QtWidgets.QLineEdit(self.centralwidget)
        self.weight_input.setObjectName("weight_input")
        self.verticalLayout.addWidget(self.weight_input)
        self.calorie_label = QtWidgets.QLabel(self.centralwidget)
        self.calorie_label.setObjectName("calorie_label")
        self.verticalLayout.addWidget(self.calorie_label, 0, QtCore.Qt.AlignHCenter)
        self.calorie_intake = QtWidgets.QLineEdit(self.centralwidget)
        self.calorie_intake.setObjectName("calorie_intake")
        self.verticalLayout.addWidget(self.calorie_intake)
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setObjectName("date_label")
        self.verticalLayout.addWidget(self.date_label, 0, QtCore.Qt.AlignHCenter)
        self.date_input = QtWidgets.QDateEdit(self.centralwidget)
        self.date_input.setAcceptDrops(True)
        self.date_input.setAutoFillBackground(False)
        self.date_input.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.date_input.setObjectName("date_input")
        self.verticalLayout.addWidget(self.date_input)
        self.Save_button = QtWidgets.QPushButton(self.centralwidget)
        self.Save_button.setObjectName("Save_button")
        self.verticalLayout.addWidget(self.Save_button)
        self.Exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.Exit_button.setObjectName("Exit_button")
        self.verticalLayout.addWidget(self.Exit_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.weight_label.setText(_translate("MainWindow", "Weight"))
        self.calorie_label.setText(_translate("MainWindow", "Calories"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.Save_button.setText(_translate("MainWindow", "Save"))
        self.Exit_button.setText(_translate("MainWindow", "Exit"))
