# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/steven/Documents/Python_code/practice/GUI/PyQt5/Health_Tracker/load_h_tracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(430, 372)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        Dialog.setFont(font)
        Dialog.setMouseTracking(False)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.exit = QtWidgets.QPushButton(Dialog)
        self.exit.setObjectName("exit")
        self.gridLayout.addWidget(self.exit, 3, 3, 1, 1)
        self.browse = QtWidgets.QPushButton(Dialog)
        self.browse.setObjectName("browse")
        self.gridLayout.addWidget(self.browse, 2, 0, 1, 1)
        self.file = QtWidgets.QTableView(Dialog)
        self.file.setObjectName("file")
        self.gridLayout.addWidget(self.file, 0, 0, 1, 4)
        self.go_back = QtWidgets.QPushButton(Dialog)
        self.go_back.setObjectName("go_back")
        self.gridLayout.addWidget(self.go_back, 3, 2, 1, 1)
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 3, 0, 1, 1)
        self.filename = QtWidgets.QLineEdit(Dialog)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exit.setText(_translate("Dialog", "Exit"))
        self.browse.setText(_translate("Dialog", "Browse"))
        self.go_back.setText(_translate("Dialog", "Go Back"))
        self.save.setText(_translate("Dialog", "Open"))
